server:
  port: ${SERVER_PORT:9090}

spring:
  application:
    name: payment-mock

payment:
  fail-rate: ${FAIL_RATE:0}       # 0-100 : % d'échecs simulés
  latency-ms: ${LATENCY_MS:100}   # latence en millisecondes

logging:
  level:
    com.ecommerce: INFO
